version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ../../
      dockerfile: infra/docker/backend.Dockerfile
    container_name: rayyan-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    env_file:
      - ../../backend/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - rayyan-network

networks:
  rayyan-network:
    driver: bridge
